http {
    map $http_x_client_type $untrusted_client_key {
        "" $binary_remote_addr;
        default "";
    }

    map $http_x_client_type $mobile_key {
        "mobile_app" $binary_remote_addr;
        default "";
    }

    map $http_x_client_type $web_key {
        "web_browser" $binary_remote_addr;
        default "";
    }

    limit_req_zone $mobile_key zone=mobile_limit:10m rate=30r/s;
    limit_req_zone $web_key zone=web_limit:10m rate=50r/s;

    # на случай непредвиденного типа клиента - занижаем пропускную способность
    limit_req_zone $untrusted_client_key zone=default_limit:10m rate=1r/s;



    server {
        listen 80;

        # Веб и мобилки сейчас обращаются на этот ресурс
        location /api/ {
            # очередь отсутствует (burst=0) - запросы сверх лимита отбиваются мгновенно со статусом  503
            limit_req zone=default_limit burst=0;
            limit_req zone=mobile_limit burst=60;
            limit_req zone=web_limit    burst=100;

            proxy_pass http://backend;
        }
    }
}